### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by qkralsgml78** [qkralsgml78/min.blog#4]
# 가설1
cpu를 낮추고 memory를 올려서 테스트를 진행하니 TPS가 너무 낮게 나왔다.
그래서 cpu를 낮게 주는 것이 TPS에 영향을 준다는 가설을 세워보고 테스트를 진행
![image](https://github.com/qkralsgml78/min.blog/assets/149050285/05adbfb7-3c52-415c-a23f-f1b0bec7a68a)
- 최고TPS: 60
- TPS: 27

**Comment by qkralsgml78** [comment]
# 가설 진행 과정
cpu만 0.10으로 올리고 테스트를 다시 진행한 결과
![image](https://github.com/qkralsgml78/min.blog/assets/149050285/4f9a243c-7118-4b46-98af-85f2cde75497)
- 최고 TPS :112
- TPS : 57.6
내 가설은 맞았지만 최고 TPS가 두배도 오르지 못했기에 **내 목표는 최고 TPS 500을 도달하는 것**\

# 2 복제파일 3개, cpu 0.25로 변경후 테스트
```
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  blog:
    # build: ../../docker_file/httpd
    image: minhee84/blog-tomsawyer
    deploy:
      mode: replicated
      replicas: 3 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 70M
        reservations:
          cpus: '0.01'
          memory: 20M
```

![image](https://github.com/qkralsgml78/min.blog/assets/149050285/13d438fa-1328-4ed7-8201-7f784bfdb2a8)

- 결과는 error로 테스트 실패, TPS도 낮게 나왔다.
